// import {poppins} from "next/font";
// import type { Metadata } from "next";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <link
//           href="https://fonts.googleapis.com/css2?family=Helvetica+Neue:wght@100;400;700&family=Poppins:wght@100;400;700&display=swap"
//           rel="stylesheet"
//         />
//       </head>
//       <body className="antialiased">
//         {children}
//       </body>
//     </html>
//   );
// }




// import { Poppins } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs';


// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["100", "400", "700"],
//   variable: "--poppins",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

    <html lang="en" className="antialiased">
      <head>
        <link 
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" 
          rel="stylesheet" 
          />
      </head>
      <body className="antialiased font-poppins">
      {/* <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn> */}
        {children}
      </body>
    </html>
          </ClerkProvider>
  );
  
}
